# New ports collection makefile for:	p5-Net-DirectConnect-TigerHash
# Date created:		2010-11-23
# Whom:			Oleg Alexeenkov <proler@gmail.com>
#
# $FreeBSD$
#

PORTNAME=	Net-DirectConnect-TigerHash
PORTVERSION=	0.03
CATEGORIES=	net-p2p net perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	proler@gmail.com
COMMENT=	Perl Direct Connect TigerHash module.

PERL_CONFIGURE=	yes
CC=	g++

.include <bsd.port.pre.mk>
.include <bsd.port.post.mk>
