# New ports collection makefile for:	p5-Net-DirectConnect
# Date created:		2010-01-16
# Whom:			Oleg Alexeenkov <proler@gmail.com>
#
# $FreeBSD$
#

PORTNAME=	Net-DirectConnect
PORTVERSION=	0.04
#PORTREVISION=	0
#PORTEPOCH=	0
CATEGORIES=	net-p2p net perl5
MASTER_SITES=	CPAN
#MASTER_SITE_SUBDIR=authors/id/P/PR/PRO
PKGNAMEPREFIX=	p5-
#PKGNAMESUFFIX=
#DISTNAME=OB
#EXTRACT_SUFX=
#DISTFILES=
#DIST_SUBDIR=	${PORTNAME}
#EXTRACT_ONLY=

MAINTAINER=	proler@gmail.com
COMMENT=	Direct Connect lib and client.

#RUN_DEPENDS=

#BUILD_DEPENDS=<>${SITE_PERL}/${PERL_ARCH}/List/Util.pm:${PORTSDIR}/lang/p5-Scalar-List-Utils \
#<------><------>${SITE_PERL}/TAP/Harness.pm:${PORTSDIR}/devel/p5-Test-Harness \
# todo: MIME::Base32 Sys::Sendfile

PERL_CONFIGURE=	yes

.include <bsd.port.pre.mk>
.include <bsd.port.post.mk>
